package enums

import (
	"godiscord.foo.ng/lib/pkg/types"
)

var Permission = struct {
	CreateInstantInvite       types.Permission
	KickMembers               types.Permission
	BanMembers                types.Permission
	Administrator             types.Permission
	ManageChannels            types.Permission
	ManageGuild               types.Permission
	AddReactions              types.Permission
	ViewAuditLog              types.Permission
	PrioritySpeaker           types.Permission
	Stream                    types.Permission
	ViewChannel               types.Permission
	SendMessages              types.Permission
	SendTTSMessages           types.Permission
	ManageMessages            types.Permission
	LinkEmbeds                types.Permission
	AttachFiles               types.Permission
	ReadMessageHistory        types.Permission
	MentionEveryone           types.Permission
	UseExternalEmojis         types.Permission
	ViewGuildInsights         types.Permission
	Connect                   types.Permission
	Speak                     types.Permission
	MuteMembers               types.Permission
	DeafenMembers             types.Permission
	MoveMembers               types.Permission
	UseVoiceActivityDetection types.Permission
	ChangeNickname            types.Permission
	ManageNicknames           types.Permission
	ManageRoles               types.Permission
	ManageWebhooks            types.Permission
	ManageGuildExpressions    types.Permission
	UseApplicationCommands    types.Permission
	RequestToSpeak            types.Permission
	ManageEvents              types.Permission
	ManageThreads             types.Permission
	CreatePublicThread        types.Permission
	CreatePrivateThread       types.Permission
	UseExternalStickers       types.Permission
	SendMessagesInThreads     types.Permission
	UseEmbeddedActivities     types.Permission
	ModerateMembers           types.Permission
	ViewMonetizationAnalytics types.Permission
	UseSoundboard             types.Permission
	CreateGuildExpressions    types.Permission
	CreateEvents              types.Permission
	UseExternalSounds         types.Permission
	SendVoiceMessages         types.Permission
	SendPolls                 types.Permission
	UseExternalApps           types.Permission
}{
	CreateInstantInvite:       types.Permission_CreateInstantInvite,
	KickMembers:               types.Permission_KickMembers,
	BanMembers:                types.Permission_BanMembers,
	Administrator:             types.Permission_Administrator,
	ManageChannels:            types.Permission_ManageChannels,
	ManageGuild:               types.Permission_ManageGuild,
	AddReactions:              types.Permission_AddReactions,
	ViewAuditLog:              types.Permission_ViewAuditLog,
	PrioritySpeaker:           types.Permission_PrioritySpeaker,
	Stream:                    types.Permission_Stream,
	ViewChannel:               types.Permission_ViewChannel,
	SendMessages:              types.Permission_SendMessages,
	SendTTSMessages:           types.Permission_SendTTSMessages,
	ManageMessages:            types.Permission_ManageMessages,
	LinkEmbeds:                types.Permission_LinkEmbeds,
	AttachFiles:               types.Permission_AttachFiles,
	ReadMessageHistory:        types.Permission_ReadMessageHistory,
	MentionEveryone:           types.Permission_MentionEveryone,
	UseExternalEmojis:         types.Permission_UseExternalEmojis,
	ViewGuildInsights:         types.Permission_ViewGuildInsights,
	Connect:                   types.Permission_Connect,
	Speak:                     types.Permission_Speak,
	MuteMembers:               types.Permission_MuteMembers,
	DeafenMembers:             types.Permission_DeafenMembers,
	MoveMembers:               types.Permission_MoveMembers,
	UseVoiceActivityDetection: types.Permission_UseVoiceActivityDetection,
	ChangeNickname:            types.Permission_ChangeNickname,
	ManageNicknames:           types.Permission_ManageNicknames,
	ManageRoles:               types.Permission_ManageRoles,
	ManageWebhooks:            types.Permission_ManageWebhooks,
	ManageGuildExpressions:    types.Permission_ManageGuildExpressions,
	UseApplicationCommands:    types.Permission_UseApplicationCommands,
	RequestToSpeak:            types.Permission_RequestToSpeak,
	ManageEvents:              types.Permission_ManageEvents,
	ManageThreads:             types.Permission_ManageThreads,
	CreatePublicThread:        types.Permission_CreatePublicThread,
	CreatePrivateThread:       types.Permission_CreatePrivateThread,
	UseExternalStickers:       types.Permission_UseExternalStickers,
	SendMessagesInThreads:     types.Permission_SendMessagesInThreads,
	UseEmbeddedActivities:     types.Permission_UseEmbeddedActivities,
	ModerateMembers:           types.Permission_ModerateMembers,
	ViewMonetizationAnalytics: types.Permission_ViewMonetizationAnalytics,
	UseSoundboard:             types.Permission_UseSoundboard,
	CreateGuildExpressions:    types.Permission_CreateGuildExpressions,
	CreateEvents:              types.Permission_CreateEvents,
	UseExternalSounds:         types.Permission_UseExternalSounds,
	SendVoiceMessages:         types.Permission_SendVoiceMessages,
	SendPolls:                 types.Permission_SendPolls,
	UseExternalApps:           types.Permission_UseExternalApps,
}
