package enums

type GuildFeature string

const (
	GF_AnimatedBanner                  GuildFeature = "ANIMATED_BANNER"
	GF_AnimatedIcon                    GuildFeature = "ANIMATED_ICON"
	GF_ApplicationCommandPermissionsV2 GuildFeature = "APPLICATION_COMMAND_PERMISSIONS_V2"
	GF_AutoModeration                  GuildFeature = "AUTO_MODERATION"
	GF_Banner                          GuildFeature = "BANNER"
	GF_Community                       GuildFeature = "COMMUNITY"
	GF_MonetizationEnabled             GuildFeature = "CREATOR_MONETIZABLE_PROVISIONAL"
	GF_StorePageEnabled                GuildFeature = "CREATOR_STORE_PAGE"
	GF_SupportServer                   GuildFeature = "DEVELOPER_SUPPORT_SERVER"
	GF_Discoverable                    GuildFeature = "DISCOVERABLE"
	GF_Featurable                      GuildFeature = "FEATURABLE"
	GF_InvitesDisabled                 GuildFeature = "INVITES_DISABLED"
	GF_InviteSplash                    GuildFeature = "INVITE_SPLASH"
	GF_VerificationGateEnabled         GuildFeature = "MEMBER_VERIFICATION_GATE_ENABLED"
	GF_IncreasedSoundCount             GuildFeature = "MORE_SOUNDBOARD"
	GF_IncreasedStickerCount           GuildFeature = "MORE_STICKERS"
	GF_News                            GuildFeature = "NEWS"
	GF_Partnered                       GuildFeature = "PARTNERED"
	GF_PreviewEnabled                  GuildFeature = "PREVIEW_ENABLED"
	GF_RaidAlertsDisabled              GuildFeature = "RAID_ALERTS_DISABLED"
	GF_RoleIcons                       GuildFeature = "ROLE_ICONS"
	GF_SubscriptionRoles               GuildFeature = "ROLE_SUBSCRIPTIONS_AVAILABLE_FOR_PURCHASE"
	GF_SubscriptionRolesEnabled        GuildFeature = "ROLE_SUBSCRIPTIONS_ENABLED"
	GF_HasCreatedSoundboardSounds      GuildFeature = "SOUNDBOARD"
	GF_TicketedEventsEnabled           GuildFeature = "TICKETED_EVENTS_ENABLED"
	GF_CustomURL                       GuildFeature = "VANITY_URL"
	GF_Verified                        GuildFeature = "VERIFIED"
	GF_HasAccessToVIPRegions           GuildFeature = "VIP_REGIONS"
	GF_WelcomeScreenEnabled            GuildFeature = "WELCOME_SCREEN_ENABLED"
)
